defaultContentLanguage: en
defaultContentLanguageInSubdir: false

frontmatter:
  date:
    - :filename
    - date

baseURL: "https://draft.tarantsov.com/"
languages:
  en:
    title: "Andrey Tarantsov on cutting-edge tech and beautiful tools"
    copyright: "By Andrey Tarantsov in 2018–2021."
    weight: 1

permalinks:
  posts: /:year/:month/:slug/
